### ISSUE TITLE
Theme not loaded over HTTPS

### ISSUE THREAD

**Issue by ghost** [ecj2/kaku#21]
Particularly with the admin interface, you want to login with HTTPS. Right now Kaku uses {%blog_url%}/path/to/css to load the CSS for admin (it's different for the main theme), and blog_url is initialized with HTTP if you visit the install page normally. This causes some browsers to not load the css.

My solution was to add a special {%http%} tag that converts to either https:// or http:// depending on the protocol being used. I edited the admin theme pages to use it, then edited the normal theme to use it too (they seem to use {%theme_directory%}/{%theme_name%} instead of {%blog_url%}... I changed my {%theme_directory%} to be just the directory portion and prepended {%blog_url%}. Finally I changed my {%blog_url%} to remove the http://.

**Comment by ecj2** [comment]
By default, the blog-wide protocol is determined when you first install Kaku, and is saved to the `{%blog_url%}` tag. It does not dynamically determine the protocol on each page, but uses `{%blog_url%}` globally. As for `{%theme_directory%}`, it points to `{%blog_url%}/content/themes`.

Currently there are a slew of bugs in the admin panel under the 1.0 and master branches. Branch 1.1 features a complete re-write of the core system, and fixes a lot of bugs. It's not ready for normal use yet, as the admin panel needs to be rewritten. Once the admin panel is rewritten in 1.1 (sometime this week, hopefully), I'll try to incorporate your suggestions.

**Comment by ecj2** [comment]
I rewrote the admin panel yesterday for the 1.1 branch (8977562), and even added the ability to reset user passwords (afb07af). Now I can move on to this.

You mentioned blog_url is initialized with HTTP by the install script normally. In the 1.1 branch, the protocol code is much better, and accurately determines HTTP vs HTTPS upon installation. Check out the [utility](https://github.com/ecj2/kaku/blob/1.1/core/classes/utility.php#L23) class for details.

In 1.1, if your site supports HTTPS upon the initial install, HTTPS will be used globally. Are you suggesting using HTTPS on the basis of per-page availability, instead of globally?

Also, the tags used in stylesheets have changed in 1.1. Both [front-end](https://github.com/ecj2/kaku/blob/1.1/templates/default/post.html#L7) and [back-end](https://github.com/ecj2/kaku/blob/1.1/admin/templates/default/template.html#L6) templates use the same CSS tags (with the exception being the admin panel's tags are prefixed with "admin_").

**Comment by ghost** [comment]
HTTP and HTTPS should both work regardless of how you installed, on any page. Not sure if that's what you did.

**Comment by ecj2** [comment]
That can be done, but would potentially pose an issue with Disqus. Disqus separates forums between HTTP and HTTPS. So http://example.com/post/hello+world would hold generate a different forum than would https://example.com/post/hello+world, for example.

Having HTTP and HTTPS working regardless of how you installed it won't be an issue for Disqus so long as the protocol used doesn't change (for this reason Kaku currently sticks with a global protocol derived from install).

Thoughts?

**Edit**
Looks like [this](https://help.disqus.com/customer/portal/articles/472098-javascript-configuration-variables#thispageidentifier) might be a possible workaround for the Disqus issue. If so, HTTP/HTTPS anywhere shouldn't be a problem.

**Comment by ecj2** [comment]
Commit f4778be solves the Disqus issue, as far as I can tell.

It used to be that even a change in URL case (such as /post/hElLo+WoRlD from /post/hello+world) would cause Disqus to generate a new forum, but the commit fixes that by adding an identifier (uses the post ID). I did not test it with HTTPS though, as I don't have HTTPS locally nor remotely, but it should work the same for HTTPS as well.

I'll work on making {%blog_url%} (and anything that uses it, like {%template_directory%}) dynamically select the protocol, instead of having it set only once at initial install.

**Comment by ecj2** [comment]
Commit 29697db implements your suggestion in the 1.1 branch. The protocol is now determined on a per-page basis, rather than being fixed after initial install.
